name: mpl351
on:
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install matplotlib==3.5.1
        python -m pip install flake8 pytest pandas
        python -m pip install numpy
    - name: Test with unittest
      run: |
        conda install pytest
        pip install coverage
        pip install codecov
        pip install python-coveralls

        coverage run -m unittest tests.test_main
        coverage run -m unittest tests.tests_utils
        coverage run -m unittest tests.test_taylor_plot
